#
# https://artifacthub.io/packages/helm/bitnami/mlflow
# https://github.com/bitnami/charts/blob/main/bitnami/mlflow/values.yaml
#
#
tracking:
  service:
    type: ClusterIP

  # temporary user / pass here, should be in the secret
  auth:
    enabled: true
    username: user
    password: "6440921D-2493-42AA-BE40-428CD753D81D"

run:
  enabled: false

minio:
  enabled: false

externalS3:
  host: "risingwave-minio.risingwave.svc.cluster.local"
  port: 9000
  useCredentialsInSecret: true
  existingSecret: "mlflow-minio-secret"
  existingSecretAccessKeyIDKey: "AccessKeyID"
  existingSecretKeySecretKey: "SecretKey"
  protocol: "http"
  bucket: "mlflow-d971"
  serveArtifacts: true

postgresql:
  enabled: false

externalDatabase:
  dialectDriver: "postgresql"
  host: "risingwave-postgresql.risingwave.svc.cluster.local"
  port: 5432
  user: mlflow
  database: mlflow
  password: mlflow
